version: '3.3'

        services:
        db:
        platform: linux/amd64
        image: mysql:5.7
        volumes:
        - db_data:/var/lib/mysql
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress

        wordpress:
        platform: linux/amd64
        depends_on:
        - db
        image: wordpress:latest
        ports:
        - "8000:80"
        restart: always
        environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_TABLE_PREFIX: ZwMoC6PX_
        volumes:
        - ./wordpress:/var/www/html

        wpcli:
        platform: linux/amd64
        depends_on:
        - wordpress
        - db
        image: wordpress:cli
        volumes:
        - ./wordpress:/var/www/html
        user: www-data
        environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_TABLE_PREFIX: ZwMoC6PX_

        phpmyadmin:
        platform: linux/amd64
        image: phpmyadmin/phpmyadmin
        links:
        - db
        environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: somewordpress
        ports:
        - 8080:80

        volumes:
        db_data: {}